### ISSUE TITLE
lib is not defined

### ISSUE THREAD

**Issue by ryanzhangau** [Solifugus/fpdf-njs#5]
When running Cell(), it give me error: 
```
ReferenceError: lib is not defined
```
```
   at FPDF.GetStringWidth (D:\anctech-invoice-server\node_modules\fpdf-njs\fpdf.js:359:3)
   at FPDF.Cell (D:\anctech-invoice-server\node_modules\fpdf-njs\fpdf.js:619:26)
```

**Comment by salvador-hernandez** [comment]
Hello.
I got the same error when trying to center the text. I solved it by changing line 359 of file fpdf.js from this **xl = lib.strlen(xs);** to this **xl = xs.length;**

I also modified the file fpdf/fonts/helvetica.js to generate a key value pairs array.
this is an extract.

var fontCodes = Array();
fontCodes[String.fromCharCode(0)]=278;
fontCodes[String.fromCharCode(1)]=278;
fontCodes[String.fromCharCode(2)]=278
fontCodes[String.fromCharCode(3)]=278;
fontCodes[String.fromCharCode(4)]=278;
.
.
fontCodes["B"] = 667;
fontCodes["C"] = 722;
fontCodes["D"] = 722;
fontCodes["E"] = 667;
fontCodes["F"] = 611;
fontCodes["G"] = 778;
fontCodes["H"] = 722;
fontCodes["I"] = 278;
.
.
module.exports = fontCodes;

I hope this can help somebody.
